name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'  # 使用合适的 Go 版本

      - name: Install FUSE library
        run: sudo apt-get install -y libfuse-dev  # 安装 FUSE 库

      - name: Go mod tidy
        run: go mod tidy  # 清理并更新 go.mod

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
